services:
  php:
    build:
      context: .
      target: app_php
    restart: always
    volumes:
      - php_socket:/var/run/php
      - ./var/log:/srv/app/var/log/
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

  nginx:
    build:
      context: .
      target: app_nginx
    restart: always
    ports:
      - ${HTTP_PORT:-8100:80}
    volumes:
      - php_socket:/var/run/php
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx/
    depends_on:
      - php

  db:
      image: mysql:9.4.0
      environment:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: app
          MYSQL_USER: app
          MYSQL_PASSWORD: 123456
      restart: always
      ports:
          - "3306:3306"

volumes:
  php_socket:


###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
